### ISSUE TITLE
Timeout waiting for window to load

### ISSUE THREAD

**Issue by NeoJist** [TormStorm/jagex-launcher-linux#41] opened 2023-07-12 02:30 UTC
no matter what i try, i keep getting timeout waiting for window to load when its trying to open the jagex launcher install:

![Screenshot_003](https://github.com/TormStorm/jagex-launcher-linux/assets/62086795/13265dbc-6779-44e8-9a0c-f6cd7a8ce46d) 

here are some errors that are spammed in the terminal
 <sub>Fontconfig error: "/etc/fonts/conf.d/05-flatpak-fontpath.conf", line 6: invalid attribute 'salt'
Fontconfig error: "/etc/fonts/conf.d/05-flatpak-fontpath.conf", line 7: invalid attribute 'salt'
Fontconfig warning: "/run/host/font-dirs.xml", line 4: unknown element "remap-dir"
Fontconfig error: "/run/host/font-dirs.xml", line 4: invalid attribute 'as-path'
Fontconfig warning: "/run/host/font-dirs.xml", line 5: unknown element "remap-dir"
Fontconfig error: "/run/host/font-dirs.xml", line 5: invalid attribute 'as-path'
Fontconfig error: Cannot load config file from /run/host/font-dirs.xml
Fontconfig warning: "/etc/fonts/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
Fontconfig warning: "/etc/fonts/conf.d/05-flatpak-fontpath.conf", line 5: unknown element "reset-dirs"
Fontconfig error: "/etc/fonts/conf.d/05-flatpak-fontpath.conf", line 6: invalid attribute 'salt'<sub>

system:

![Screenshot_004](https://github.com/TormStorm/jagex-launcher-linux/assets/62086795/89a62e30-14c2-45bf-bf41-c50f12f00897)

 
any help is appreciated :)

**Comment by guydols** [comment] 2023-07-12 12:03
I'm currently experiencing the same problem. I haven't found a way to solve or circumvent the error.

**Comment by NeoJist** [comment] 2023-07-12 13:32
also just loops on this indefinitely after pressing okay on the timeout window:

<sub>Checking directory size...
awk '{ print $1 }'
du -sh '/home/julian/Games/jagex-launcher/drive_c/Program Files (x86)/Jagex Launcher'
 echo 0G
dir_size=0G
sed 's/.$//'
echo 0G
dir_size=0
((  0 > 200  ))
((  0 > 1  ))
sleep 10<sub>

**Comment by jacob-thompson** [comment] 2023-07-12 17:56
same issue here with the loop during install process.

**Comment by tuba000** [comment] 2023-07-12 18:08
Same loop here, but only without any errors.

**Comment by nmlynch94** [comment] 2023-07-13 17:40
There is a bug in Lutris where it doesn't always default to the correct version of Proton-GE if it isn't already installed. Please double check under your Wine runners and make sure that is added. Let me know if it is and I can try to reproduce this.

Also please double-check that the install directory you are choosing is empty before you start.

The installer window can't be closed by the window manager. It needs to be killed from the cli or it just hangs forever. That script is monitoring the install directory so it knows when it can kill the process without the user needing to intervene. Since the installer isn't working, it is stuck checking until the lutris installer is aborted.

**Comment by NeoJist** [comment] 2023-07-13 19:56
> There is a bug in Lutris where it doesn't always default to the correct version of Proton-GE if it isn't already installed. Please double check under your Wine runners and make sure the latest Proton GE version is added. Let me know if it is and I can try to reproduce this.
> 
> Also please double-check that the install directory you are choosing is empty before you start.
> 
> The installer window can't be closed by the window manager. It needs to be killed from the cli or it just hangs forever. That script starts when the installer is launcher and is monitoring the install directory so it knows when the user has continued through the installer and it can kill the process without the user needing to use kill/xkill. Since the jagex installer isn't working, it is stuck checking until the lutris installer is aborted.
> 
> We have had this bug reported a few times and have been able to intermittently reproduce it, but we haven't been able to nail down the exact cause. If anyone is a Wine maven, would welcome some advice on how to track it down.



i just retried the exact same jagexlauncher.yml script that i had downloaded on tuesday, i changed ABSOLUTELY NOTHING, and it just magically worked, whole process took like a minute lol.

**Comment by nmlynch94** [comment] 2023-07-13 21:04
Yeah we are still working around some edge cases/lutris bugs, but glad it's working for you now!

I've experienced similar behavior in the past so don't worry you're not going crazy :). Problem is, I can't reproduce it consistently.

**Closed** 2023-07-13 22:12 UTC

**Comment by buttrknife** [comment] 2023-07-27 16:40
Hello, I am encountering the same error. I read something about switching Feral Game Mode (I dont know what that means) and that did not help. I have the same version of Proton GE as above. I ensured the chosen directory was empty before beginning installation. I am still encountering this :(

I am very new to using Linux, and it is not wildly important to me to have this working, but I would like to have it functional at some point. I am willing to upload any log files or whatever else you may need but I would likely need help locating such. I am on Ubuntu 22.04.2, basically completely fresh install. Thank you!

**Comment by Ivor808** [comment] 2023-08-08 02:14
> Hello! I've been testing a fix for this issue. Could you please try out this version of the file https://github.com/nmlynch94/jagex-launcher-linux/blob/patch-14/resources/jagexlauncher.yml and see if you have any luck?

Hey so I've been hitting this issue. I tried your file + changing the default wine version to the proton one. No luck still. It just loops on failing the window and this 

`Checking directory size...
++ awk '{ print $1 }'
++ du -sh '/home/ivor/Games/jagex-launcher/drive_c/Program Files (x86)/Jagex Launcher'
++ echo 0G
+ dir_size=0G
++ echo 0G
++ sed 's/.$//'
+ dir_size=0
+ ((  0 > 200  ))
+ ((  0 > 1  ))
+ sleep 10`

**Comment by nmlynch94** [comment] 2023-08-08 14:13
Those logs are just the bash script running in debug mode. It is working normally. I'd need to see the rest of them to potentially see why the installer didn't open. Try the latest version of the script on the main branch.

**Comment by Ivor808** [comment] 2023-08-08 19:39
> Those logs are just the bash script running in debug mode. It is working normally. I'd need to see the rest of them to potentially see why the installer didn't open. Try the latest version of the script on the main branch.

Got it. Here is the full errors logs https://pastebin.com/RA5igCsJ

**Comment by loftwing** [comment] 2023-08-20 09:01
> Hello! I've been testing a fix for this issue. Could you please try out this version of the file https://github.com/nmlynch94/jagex-launcher-linux/blob/patch-14/resources/jagexlauncher.yml and see if you have any luck?

This is the only thing that has worked for me on EndeavourOS

**Comment by discnnectd** [comment] 2023-08-21 08:29
> > Hello! I've been testing a fix for this issue. Could you please try out this version of the file https://github.com/nmlynch94/jagex-launcher-linux/blob/patch-14/resources/jagexlauncher.yml and see if you have any luck?
> 
> This is the only thing that has worked for me on EndeavourOS

I'm new to Linux so won't be able to help much, but I didn't get this to work using a fresh install of EndeavourOS.
I originally was using Windows 11 with a Mint Cinnamon vm and it worked first try. I then reset my pc to native Mint with no luck. I then tried Arch, and now EndeavourOS with no luck of getting it to work like before. This is the exact issue I'm having I believe. I've tried the most recent yaml (which is the one that worked first try) and can't even get it to work with the yaml posted here.

**Comment by ingokuba** [comment] 2023-08-28 19:45
I am encountering the same problem. The directory "`${GAMEDIR}/drive_c/Program Files (x86)/Jagex Launcher`" is never created but some other in `${GAMEDIR}/drive_c/Program Files (x86)/` are being created. Or does it take hours to install?

**Comment by nmlynch94** [comment] 2023-09-10 08:20
@ingokuba @discnnectd Please try this script and see if you have anymore luck https://github.com/nmlynch94/jagex-launcher-linux/blob/main/resources/jagexlauncher.yml. It should not take hours. The installer window should show up within 2 minutes or so.

If that doesn't work, please try this method https://github.com/TormStorm/jagex-launcher-linux/issues/75#issuecomment-1694724713 which will bypass the installer. If you get

**Comment by jamesryan-dev** [comment] 2025-03-12 20:38
+1 experiencing on mac
