### ISSUE TITLE
RuneLite is not launching while in game mode.

### ISSUE THREAD

**Issue by Otkar** [TormStorm/jagex-launcher-linux#88] opened 2023-09-19 00:14 UTC
**Describe the bug**
Since this [commit](https://github.com/TormStorm/jagex-launcher-linux/commit/8212633337a2591ac4858b15552a4c92e95d8751), it is no longer possible to launch RuneLite in game mode (works in desktop mode.)

**To Reproduce**
1. Follow the installation steps to the letter.
2. Launch the launcher in game mode.
3. Launch RuneLite.
4. Nothing happens...

**Expected behavior**
The client RuneLite should launch.

**Please complete the following information:**
 - Distro : Steamdeck 
 - Game mode 
 - Version

**Additional context**

**Comment by TormStorm** [comment] 2023-09-19 13:33
Duplicate of #83

**Closed by TormStorm** 2023-09-19 13:33 UTC
Labels: duplicate
