### ISSUE TITLE
Runelite flatpak issue 

### ISSUE THREAD

**Issue by Ajmart99** [TormStorm/jagex-launcher-linux#101] opened 2023-10-04 06:11 UTC
Starters on the steam deck I used flatpak to install runelite runes in desktop mode but when I go to game mode it won't run.

**Comment by Calmata** [comment] 2023-10-04 06:43
Hi!
Is it that the Jagex Launcher itself won't start, or is it that RuneLite doesn't launch?

If it's the latter, I believe we are working on a change specifically to address this problem, which should be out within the next couple of days.

If you can't spare time to get back in the game (clan obligations etc.) and don't mind using a 3rd party launcher, one of the contributors to this project, Adamcake, has created a simple native launcher which is available over on flathub:

https://flathub.org/apps/com.adamcake.Bolt

I use that myself, but obviously it comes with an "at your own risk" warning,

**Comment by TormStorm** [comment] 2023-10-04 06:51
Probably a duplicate of #83, got a fix for this on the way.

**Comment by Dizected** [comment] 2023-10-05 10:02
Got the same Issue, will run in desktop mode, but game mode just shows a ... after pressing play then it goes back to saying 'play' with nothing happening? Anyone have any idea's to fix this? And any news when a fix would be ready?

**Comment by Dizected** [comment] 2023-10-05 10:54
Thanks for the fast reply Torm, would I only need to use the most recent installation script for the flatpak version to fix this issue via litrus? Sorry to sound like a complete noob, but kinda new to Linux systems.

**Comment by TormStorm** [comment] 2023-10-05 11:13
> Thanks for the fast reply Torm, would I only need to use the most recent installation script for the flatpak version to fix this issue via litrus? Sorry to sound like a complete noob, but kinda new to Linux systems.

No worries, you use the non-native installation script in you are on a Steam Deck :)

**Comment by TormStorm** [comment] 2023-10-09 23:20
Resolved with #100

**Closed by TormStorm** 2023-10-09 23:20 UTC
