### ISSUE TITLE
Python command in install script points to the wrong version of python

### ISSUE THREAD

**Issue by TuxDeluxe** [TormStorm/jagex-launcher-linux#109] opened 2023-10-26 05:08 UTC
**Describe the bug**
In OpenSuse Tumbleweed, the command "python" is linked to python2 in /usr/bin, this is a problem because the .yaml install script uses python (2) to execute commands from modules provided in python3. So when the script runs, it produces an error and cannot continue as it cannot find the modules pip or venv. The solution in my case, was to change the instances of the command python in the .yaml to python3. This is an OpenSuse Tumbleweed specific issue but other distros may have this issue also, I have not checked. I believe changing the command to python3 will also work for those unaffected as on both distros it should link to python version 3 but I have not tested that.

**To Reproduce**
1. Be on the linux distro OpenSuse Tumbleweed
2. Use the latest install script unchanged to install the jagex launcher through lutris

**Expected behavior**
Python command correctly points to python version 3 in order to use the two modules: venv and pip and complete successfully allowing you to continue with the installation.

**Screenshots**
![Screenshot_20231026_150624](https://github.com/TormStorm/jagex-launcher-linux/assets/98460230/79bdd34f-d7d3-422e-af20-8555116129a4)

<details>
<summary><strong>Hardware Information</strong></summary>

[System]
OS:              openSUSE Tumbleweed 20231023 n/a
Arch:            x86_64
Kernel:          6.5.8-1-default
Desktop:         KDE
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 3 3300X 4-Core Processor
Physical cores:  4
Logical cores:   8

[Memory]
RAM:             15.5 GB
Swap:            2.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 5600 XT (navi10, LLVM 17.0.2, DRM 3.54, 6.5.8-1-default)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.2.1
OpenGL Core:     4.6 (Core Profile) Mesa 23.2.1
OpenGL ES:       OpenGL ES 3.2 Mesa 23.2.1
Vulkan Version:  1.3.261
Vulkan Drivers:  AMD Radeon RX 5600 XT (RADV NAVI10) (1.3.255)
</details>

**Additional context**
I should say that my problem is fixed but thought I would let you know in case it causes problems in future.

**Comment by TormStorm** [comment] 2023-10-26 06:40
Are you using the Lutris Flatpak?

**Comment by TuxDeluxe** [comment] 2023-10-26 07:36
No, I'm using the lutris package that comes in the default OpenSuse repos. Namely from the openSUSE-Tumbleweed-Oss repo.

**Comment by TormStorm** [comment] 2023-10-26 07:42
Duplicate of #108 We recommend using the Flatpak version of Lutris to avoid dependency issues. If you are not using Flatpak you can reference the troubleshooting section of the [Wiki](https://github.com/TormStorm/jagex-launcher-linux/wiki) to see what you need to try to get it working, but your results may vary.

**Closed by TormStorm** 2023-10-26 07:42 UTC
Labels: duplicate
