### ISSUE TITLE
Jagex Launcher won't open RuneLite in Game Mode on Steam Deck

### ISSUE THREAD

**Issue by Kingbald** [TormStorm/jagex-launcher-linux#92] opened 2023-09-26 04:01 UTC
**Describe the bug**
The RuneLite client will not launch via Game Mode on the Steam Deck via the Jagex Launcher, however it is able to open via Desktop Mode.

**To Reproduce**

1. Installed Jagex Launcher via Lutris local script
2. Logged into the launcher via Desktop mode and confirmed is working
3. Installed RuneLite via discovery store
4. Installed BoilR via discovery store and imported Jagex Launcher to steam
5. Swapped back to Game Mode
6. Launch Jagex Launcher via GameMode and steam
7. Click play with RuneLite selected

Whenever I try to launch RuneLite via gamemode through the launcher the play button looks pressed then goes back to normal in a few seconds without anything launching or happening.

**Expected behavior**
Runelite launches normally after pressing play on Jagex Launcher.

**Screenshots**
I can take some but haven't yet.

**Please complete the following information:**
 - Steam os 3.4.10
 - Steams default linux

**Additional context**

Sorry Steam deck is brand new and this is my first time diving into Linux so I'm pretty new and learning. Any help with this would be super appreciated. Not sure if I'm missing something or if something is wrong.

**Comment by TormStorm** [comment] 2023-09-28 09:58
Duplicate of #83

**Closed by TormStorm** 2023-09-28 09:58 UTC
Labels: duplicate
